GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzMzNzM1MzgsImV4cCI6MTYzMzM3MzUzOCwiYXVkIjoiNjE1YjNjMGI3NTY1ZjY5ZGMyNGZlMGJkIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.eyjI-kO9J0GZZk3yGV4gqXt9GLUo1pAJ_AJ2QM81NJ4

###login routh
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "zassas@gmail.com",
    "password": "12aa34s"
}


###login routh
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "email": "zassads@gmail.com",
    "password": "12aa34s"
}


###login routh
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzM0MDM3MzIsImV4cCI6MTY2NDk2MTMzMiwiYXVkIjoiNjE1YjNjMGI3NTY1ZjY5ZGMyNGZlMGJkIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.36K8VmUTM4fsAP2srWbPlM6tiEeB92DpScnwz-W7uCk"
}

###login routh
DELETE http://localhost:3000/auth/logout

